### ISSUE TITLE
希望可以支持调用ollama

### ISSUE THREAD

**Issue by linyushu520** [SengokuCola/MaiMBot#164]
### 检查项

- [x] 我确认在Issues列表中并无其他人已经建议过相似的功能
- [ ] 这个新功能可以解决目前存在的某个问题或BUG

### 期望的功能描述

如果可以调用本地ai（比如说ollama，那就太好了！

**Comment by BBleae** [comment]
理论上现在直接把.env里的base url和key改成本地运行的ollama的base url和key就能用
例如:

```properties
DEEP_SEEK_KEY=ollama
DEEP_SEEK_BASE_URL=http://localhost:11434/v1
```

然后在bot_config.toml里配置你想使用的模型:

```toml
[model.llm_normal_minor]
name = "deepseek-r1:671b"
base_url = "DEEP_SEEK_BASE_URL"
key = "DEEP_SEEK_KEY"
```

参考 [ollama/docs/openai.md at main · ollama/ollama](https://github.com/ollama/ollama/blob/main/docs/openai.md)
