### ISSUE TITLE
bot_config_toml未上传 requirements.txt 缺失 tomli nonebot2[fastapi] 以及 pydantic 版本 pydantic==1.10.0

### ISSUE THREAD

**Issue by Horldsence** [SengokuCola/MaiMBot#2]
```toml
[project]
name = "Megbot"
version = "0.1.0"
description = "New Bot Project"
dependencies = [
    "aiohttp==3.10.11",
    "apscheduler==3.11.0",
    "black==24.3.0",
    "flake8==7.0.0",
    "jieba==0.42.1",
    "loguru==0.7.3",
    "matplotlib==3.7.5",
    "networkx==3.2.1",
    "nonebot-adapter-onebot==2.2.3",
    "nonebot-plugin-apscheduler==0.4.0",
    "nonebot2[fastapi]==2.2.1",
    "numpy==1.24.4",
    "openai==1.61.0",
    "pandas==2.0.3",
    "pymongo==4.3.3",
    "pydantic==1.10.0",
    "pytest==8.1.1",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "requests==2.31.0",
    "tomli>=2.2.1",
]

[tool.nonebot]
plugins = ["src.plugins.chat"]
plugin_dirs = ["src/plugins"] 
```
uv 环境文件参考

**Comment by Horldsence** [comment]
又及：deepseek-r1基于config.py反推的bot_config.toml文件内容
```toml
[database]
host = "127.0.0.1"
port = 27017
name = "MegBot"

[emoji]
check_interval = 120
register_interval = 10

[bot]
qq = 123456789  # 这里填写机器人的QQ号

[response]
model_r1_probability = 0.3

[message]
min_text_length = 2
max_context_size = 15
emoji_chance = 0.2

[groups]
read_allowed = [123456, 789012]  # 允许读取消息的群组ID列表
talk_allowed = [123456, 789012]  # 允许发送消息的群组ID列表
talk_frequency_down = [123456]    # 降低发送消息频率的群组ID列表
```
