### ISSUE TITLE
配置指南与 bot_config.toml 实际配置文件存在不一致情况

### ISSUE THREAD

**Issue by Klu5ure** [SengokuCola/MaiMBot#317]
没看错的话，在新手配置指南和标准配置指南里面，关于bot_config.toml的配置文档是这样写的
```toml
[model.llm_reasoning] #推理模型R1，用来理解和思考的喵
name = "Pro/deepseek-ai/DeepSeek-R1"  # 模型名字
# name = "Qwen/QwQ-32B"  # 如果想用千问模型，可以把上面那行注释掉，用这个呢
base_url = "SILICONFLOW_BASE_URL"  # 使用在.env.prod里设置的服务地址
key = "SILICONFLOW_KEY"  # 使用在.env.prod里设置的密钥
```
而在 template/bot_config_template.toml 中的实际配置格式为
```toml
[model.llm_reasoning] #回复模型1 主要回复模型
name = "Pro/deepseek-ai/DeepSeek-R1"
provider = "SILICONFLOW"
pri_in = 0 #模型的输入价格（非必填，可以记录消耗）
pri_out = 0 #模型的输出价格（非必填，可以记录消耗）
```
可以看出，配置指南中使用的是base_url和key字段，而实际配置文件中使用的是provider字段
如果确实是配置指南有错误的话，请问我可以提交一个pr进行修改吗（我也好想成为贡献者
